// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9GUXsVC72E5fxCcszRk8yI_9En6ssNWI',
    appId: '1:205665310362:web:4b6d47394019013922b123',
    messagingSenderId: '205665310362',
    projectId: 'icthub-project-dff3a',
    authDomain: 'icthub-project-dff3a.firebaseapp.com',
    storageBucket: 'icthub-project-dff3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP4tqL-vPLNv5FqMlLs-UiYb0OeCBkd2o',
    appId: '1:205665310362:android:ebbc3de77cbd2bf422b123',
    messagingSenderId: '205665310362',
    projectId: 'icthub-project-dff3a',
    storageBucket: 'icthub-project-dff3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjP57xnkBuiDr7gpDh_6mkKWe8S7W3dI',
    appId: '1:205665310362:ios:1897e34bc12968bb22b123',
    messagingSenderId: '205665310362',
    projectId: 'icthub-project-dff3a',
    storageBucket: 'icthub-project-dff3a.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
